### ISSUE TITLE
Sequence diagram z-order

### ISSUE THREAD

**Issue by therealryan** [Mastercard/flow#265]
Take a squint at the sequence diagram in [this flow detail page](https://mastercard.github.io/flow/execution/latest/flow_execution_reports/example/app-itest/target/mctf/latest/detail/6AD48A1226A7921950AAE77C926869FA.html#?msg=5), in particular the horizontal message line from `QUEUE` to `CORE` - it's rendered as passing _under_ the vertical lines for `STORE` and `DB`.

It'd be better if the horizontal line were to be rendered on top.

**Comment by Chaitu-Tatipamula** [comment]
![image](https://user-images.githubusercontent.com/107246959/221155850-3616e826-d15f-43ba-8c8d-51deb01dd978.png)

is that should be like this

**Comment by therealryan** [comment]
Yeah, we want the black horizontal lines to be drawn on top of the grey vertical lines

**Comment by Chaitu-Tatipamula** [comment]
where shoul i find the source of this in the repo

**Comment by therealryan** [comment]
The vertical lines are [these divs](https://github.com/Mastercard/flow/blob/main/report/report-ng/projects/report/src/app/flow-sequence/flow-sequence.component.html#L10-L12)
The horizontal lines are [these divs](https://github.com/Mastercard/flow/blob/main/report/report-ng/projects/report/src/app/seq-action/seq-action.component.html#L21-L30)

**Comment by Chaitu-Tatipamula** [comment]
Will my commit solve this

**Comment by Chaitu-Tatipamula** [comment]
![image](https://user-images.githubusercontent.com/107246959/221230734-be3482ee-23e5-4478-a67b-db167ce31eaf.png)
check this out the black ones are on the top...!

**Comment by Chaitu-Tatipamula** [comment]
why i was unable to create a pr for this

**Comment by therealryan** [comment]
@Chaitu-Tatipamula That looks great! I have no idea why you're not able to raise a PR - what happens when you try?
You were able to raise #264, so it shouldn't be a permissions issue.

**Comment by Chaitu-Tatipamula** [comment]
check pr #274

**Comment by therealryan** [comment]
Cheers! I've left a comment on #274 - it looks like you left a change from the log-scrolling issue you worked on before. It probably doesn't belong in a PR for this issue.
